version: '3.8'

networks:
  shorts-network:
    driver: bridge
    external: true

volumes:
  shorts-data:
    name: shorts-data

services:
  redis-local:
    image: redis:latest
    container_name: redis-local
    ports:
      - '6379:6379'
    networks:
      shorts-network:
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
  shorts_dashboard:
    image: shorts_dashboard:latest
    container_name: shorts_dashboard
    ports:
      - '3005:3005'
    networks:
      shorts-network:
    depends_on:
      - 'redis-local'
    links:
      - 'redis-local'
    environment:
      - REDIS_HOST=http://redis-local
      - REDIS_PORT=6379
      - PORT=3005
      - BASE_URI=
      - USER_RATE=1000
      - URL_RATE=400
      - ACCESS_TOKEN_SECRET=65acb90771cdb3da2c4f415aef09974902c844b2c0a31367e5f1cf93a1854954
